### ISSUE TITLE
Dataset preview fails

### ISSUE THREAD

**Issue by ignatov17** [ALTERNATIVE-EU/ckanext-cloudstorage#4]
When try to preview a dataset with Explore->Preview it shows an error.

![Image](https://github.com/ALTERNATIVE-EU/platform-deployment/assets/48250340/0ce2448e-64bf-4ffc-a054-099c9b9f914c)

**Comment by darashevcstbg** [comment]
https://github.com/ALTERNATIVE-EU/ckanext-cloudstorage/pull/5 https://github.com/ALTERNATIVE-EU/platform-deployment/pull/39

**Comment by ptashev** [comment]
Tested! Fixed!
